# Generated by Django 5.2.7 on 2026-02-26 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=20)),
                ('direction', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=5)),
                ('entry_price', models.DecimalField(decimal_places=5, max_digits=12)),
                ('stop_loss', models.DecimalField(decimal_places=5, max_digits=12)),
                ('take_profit', models.DecimalField(decimal_places=5, max_digits=12)),
                ('lot_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('risk_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rr_planned', models.DecimalField(decimal_places=2, editable=False, max_digits=5)),
                ('rr_actual', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('result', models.CharField(choices=[('WIN', 'Win'), ('LOSS', 'Loss'), ('BE', 'Break Even')], max_length=5)),
                ('pnl', models.DecimalField(decimal_places=2, editable=False, max_digits=15)),
                ('session', models.CharField(choices=[('ASIAN', 'Asian'), ('LONDON', 'London'), ('NY', 'New York')], max_length=10)),
                ('setup_type', models.CharField(max_length=50)),
                ('grade', models.CharField(choices=[('A_PLUS', 'A+'), ('B', 'B')], max_length=10)),
                ('emotion_before', models.CharField(blank=True, max_length=50)),
                ('emotion_after', models.CharField(blank=True, max_length=50)),
                ('mistake_flag', models.BooleanField(default=False)),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to='trade_screenshots/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trades', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
