# Generated by Django 5.2.7 on 2026-02-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trades', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='loss_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
